Add database
IgorMartynkin1981/java-filmorate pull request #6
Opened 2022-08-14 19:49 UTC by IgorMartynkin1981

Refactor внесены изменения согласно ТЗ11

2022-08-15 15:24 UTC, kukolev requested changes

2022-08-15 22:39 UTC, IgorMartynkin1981 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage/FilmRowMapper.java
> +                //.genres(genreService.findAll(resultSet.getLong("id")))
Закомментированный код удалён

2022-08-15 22:41 UTC, IgorMartynkin1981 commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDbStorage/GenreDaoImpl.java
> +        String sqlQuery = "SELECT id, name" +
Изменения внесены

2022-08-15 22:45 UTC, IgorMartynkin1981 commented
[Refactor внесены правки согласно кодревью](https://github.com/IgorMartynkin1981/java-filmorate/pull/6/commits/fa3ed8d7fdebe457212a8539c2babe9835f8e42a)

2022-08-16 16:03 UTC, kukolev requested changes

2022-08-16 16:03 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Optional<User> findUserByEmail = users.stream().filter(user1 -> user1.getEmail().equals(user.getEmail())).findFirst();
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-16 16:03 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (id < 0) {
Валидации лучше вынести в отдельный приватный метод. Так код будет понятней.

2022-08-16 18:58 UTC, IgorMartynkin1981 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Optional<User> findUserByEmail = users.stream().filter(user1 -> user1.getEmail().equals(user.getEmail())).findFirst();
Исправлено

2022-08-16 19:04 UTC, IgorMartynkin1981 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (id < 0) {
Приватный метод создан.

2022-08-16 19:08 UTC, IgorMartynkin1981 commented
[Refactor внесены правки согласно кодревью №2](https://github.com/IgorMartynkin1981/java-filmorate/pull/6/commits/4f9f7ae73fafc14ee477d072908fb5ff47f53c6b)

2022-08-16 22:09 UTC, kukolev approved these changes

2022-08-17 06:05 UTC, merged